### ISSUE TITLE
TagRef -> String text 

### ISSUE THREAD

**Issue by Pesche007** [opentdc/workrecords-service#3]
Remove Attribute text on TagRef

**Comment by bruno63** [comment]
done

**Comment by bruno63** [comment]
/api/workrecord/{workRecordId}/tagref/{tagRefId}
Das TagRef Objekt enthält:
String tagId  (die ID des referenzierten Tags)
String text (der Text, der im Tagfeld auf dem GUI dargestellt wird. Habe diesen nun doch wie ursprünglich angedacht implementiert. Ich denke, dass du dies brauchst.
Du musst dann auch die ganze Auflösung über Tag/LocalizedText nicht machen, sondern kriegst automatisch den Text der aktuellen Sprache.

aber erneute Diskussion mit Peter zeigt, dass text auf TagRef  nicht nötig ist. Text kann immer direkt im referenzierten Tag geholt werden.

**Comment by bruno63** [comment]
Text Attribute removed
