### ISSUE TITLE
New method TaggedWorkRecord

### ISSUE THREAD

**Issue by Pesche007** [opentdc/workrecords-service#4]
New method to allow POST of WorkRecord object with single or multiple attached tagIds

**Comment by bruno63** [comment]
Please specify in more detail.
How should the data format (JSON) look like ?
z.B.
String tags 
Format :    word/lang,word/lang,word/lang etc.

**Comment by bruno63** [comment]
oder post immer nur in einer Sprache:
LanguageCode lang
String tags  (word,word,word)

**Comment by Pesche007** [comment]
Ideally, the POST would include a standard WorkRecord Object with an additional attribute tagRefIds that contanins an array of strings that represent a tagRefId. 
JSON
{
CompanyId:companyId,
ProjectId:projectid,
....
tagRefIds:['12345-1', '12345-2', 12345-3']
}

If simpler, it can also contain an array with objects, e.g. [{id:'12345-1'}, {id:'12345-2'}]

**Comment by bruno63** [comment]
Du möchtest ja wahrscheinlich nicht die tagIds im post angeben.
Denn die tag ids hast du ja zu diesem Zeitpunkt noch nicht. Die Idee ist doch, dass du im Client einen neuen Workrecord per Form anlegst und diesem auch gleich einige Tags gibts. Dabei handelt es sich um Tag-Texte in der aktuellen Sprache des Benutzers. Wenn du nun diese Daten zum Server schickst, dann muss dieser zuerst prüfen, ob es diesen Text mit dieser Sprache bereits gibt und sonst einen neuen anlegen. Erst ab dann ist die TagID bekannt.
Wenn wir aber den Tag Text schicken, dann müssen wir auch den dazugehörigen LangCode mitschicken. Der Server kann sonst nicht wissen, in welcher Sprache der Tag ist. 

Ich sehe folgende Möglichkeiten:
1) Form ausfüllen, WorkRecord posten, dann jeden Tag posten und jeden TagRef posten (so ist es jetzt)
2) Form ausfüllen, WorkRecord mit Zusatzfeld z.B. tagTexts { 'en:test,word,phrase' } posten
3) Form ausfüllen, WorkRecord posten, Liste aller TagTexte inkl. Sprache posten (neuer POST addTags('en:test,word,phrase')

wenn du einverstanden bist, würde ich nun 2) und 3) so implementieren. Bitte prüfen, ob du den String 'langCode:word{,word}' im Client so zusammen setzen kannst.

**Comment by bruno63** [comment]
gem. Telefon von heute 1827:
tagids werden auf dem client bereits aufgelöst.
Peter hätte gerne Variante 2) mit TagIDs   tags ::=  'tagId{,tagId}

**Comment by bruno63** [comment]
ok, habs nun doch gemacht:
- POST addTags
- attribute tagIdList
