### ISSUE TITLE
Cache Timer Entries

### ISSUE THREAD

**Issue by Pesche007** [opentdc/workrecords-service#5]
The timer needs to save the different project start and state-times into a database, in order to keep the data if the site is closed. Once the timer is set to stop the entry is no longer needed. 

timerObject: {
  date (date),
  companyId,
  companyTitle,
  projectId,
  projectTitle,
  timerStart (date),
  status (tinyint)
}

**Comment by wfro64** [comment]
Why not just create a work record with isOpen=true (or isRunning=true or isComplete=false)? I.e. a timer = work record with isOpen=true (or isRunning=true or isComplete=false).

**Comment by Pesche007** [comment]
Hmm... Good question. I somehow don't like the idea of have an extra attribute just because of the timer. But on the other hand the new proposed object is more or less a workRecord already... So makes little sense to save an additional workRecord-like object into another DB. Fine by me, I just hope it doesn't screw up the Service (i.e. the incomplete workRecords should only be displayed in the timer view, otherwise it get's a mess, as attributes are missing). Is that not an issue?

**Comment by bruno63** [comment]
+1 in my opinion, a boolean is an elegant solution for this. It fulfills the requirement and can be implemented on the same data structure. This makes the model usable in different WTT views (e.g. calendar, timer, list ...)
->   boolean isRunning in WorkRecordModel
implemented 16.8.15, Testcase WorkRecordListTest

**Comment by Pesche007** [comment]
We need two different attributes:
-> isRunning: the time entry is set to "Run" and runs from startAt to now
-> isPause: the time entry is set to "Pause" and has started at startAt and has run durationHours hours and durationMinutes minutes.

If simpler make one attribute status (1 = run, 2 = pause).

**Comment by bruno63** [comment]
isPaused implemented
